In [1]:
import numpy as np


In [2]:
a=np.array([3,4,5])

In [3]:
a[0]

3

In [7]:
b=np.array([[2,3],[7,4],[5,4]])

In [8]:
b.ndim

2

In [9]:
b.itemsize

4

In [11]:
b.dtype

dtype('int32')

In [12]:
b

array([[2, 3],
       [7, 4],
       [5, 4]])

In [13]:
b.shape

(3, 2)

In [43]:
c=np.array([[2,3],[7,4],[5,4]],dtype=complex)

In [15]:
b

array([[2.+0.j, 3.+0.j],
       [7.+0.j, 4.+0.j],
       [5.+0.j, 4.+0.j]])

In [16]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.arange(1,5)

array([1, 2, 3, 4])

In [20]:
np.arange(1,5,2)

array([1, 3])

In [21]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [22]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [23]:
b.reshape(2,3)

array([[2.+0.j, 3.+0.j, 7.+0.j],
       [4.+0.j, 5.+0.j, 4.+0.j]])

In [26]:
b.reshape(2,2)

ValueError: cannot reshape array of size 6 into shape (2,2)

In [30]:
c=b.ravel()

In [29]:
b

array([[2.+0.j, 3.+0.j],
       [7.+0.j, 4.+0.j],
       [5.+0.j, 4.+0.j]])

In [31]:
c

array([2.+0.j, 3.+0.j, 7.+0.j, 4.+0.j, 5.+0.j, 4.+0.j])

In [32]:
b.min()

(2+0j)

In [33]:
b.max()

(7+0j)

In [34]:
b.sum()

(25+0j)

In [35]:
a.sum(axis=0)

12

In [36]:
b.sum(axis=0)

array([14.+0.j, 11.+0.j])

In [37]:
np.sqrt(a)


array([1.73205081, 2.        , 2.23606798])

In [38]:
a

array([3, 4, 5])

In [39]:
np.std(a)

0.816496580927726

In [40]:
a+b

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

In [41]:
a

array([3, 4, 5])

In [46]:
d=np.array([1,2,3])

In [47]:
a+d

array([4, 6, 8])

In [48]:
a_b

NameError: name 'a_b' is not defined

In [49]:
a-b

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

In [50]:
a-d

array([2, 2, 2])

In [52]:
a*d

array([ 3,  8, 15])

In [53]:
a/d

array([3.        , 2.        , 1.66666667])

In [54]:
a.dot(d)

26